# Generated by Django 4.1 on 2022-10-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_customuser_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
